services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - AUTH_USERNAME=${AUTH_USERNAME}
            - AUTH_PASSWORD=${AUTH_PASSWORD}
            - DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING}
            - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
            - ELASTICSEARCH_INDEX=${ELASTICSEARCH_INDEX}
            - ELASTICSEARCH_URL=${ELASTICSEARCH_URL} 
        ports:
            - "8080:8080"
        depends_on:
            - db
        networks:
            - cdsNetwork

    db:
        image: mysql:latest
        env_file: "DatabaseEnv.env"
        volumes:
            - ./MySQLInit.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - cdsNetwork

networks:
    cdsNetwork: {}

volumes:
    db_data: {}