services:
    app:
        env_file:
            - env/app_variables.env
            - env/version.env
        build:
            context: .
            dockerfile: Dockerfile
        image: app
        ports:
            - "8080:8080"
        depends_on:
            - db
        environment:
            - ASPNETCORE_URLS=http://+:5189
        networks:
            - cdsNetwork

    db:
        env_file:
            - env/database_variables.env
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - ./MySQLInit.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - cdsNetwork

networks:
    cdsNetwork: {}

volumes:
    db_data: {}
