services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: 
            - path: "DefaultAppEnv.env"
              required: true # default env file
            - path: "ProductionAppEnv.env"
              required: false # production env file -> overrides values from DefaultAppEnv.env if set
        ports:
            - "8080:8080"
        depends_on:
            - db
        networks:
            - cdsNetwork

    db:
        image: mysql:latest
        env_file: 
            - path: "DefaultDatabaseEnv.env"
              required: true # default env file
            - path: "ProductionDatabaseEnv.env"
              required: false # production env file -> overrides values from DefaultDatabaseEnv.env if set
        volumes:
            - ./MySQLInit.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - cdsNetwork

networks:
    cdsNetwork: {}

volumes:
    db_data: {}