name: Docker Image CI/CD

on:
    pull_request:
        branches: [ "main" ]
    schedule:
        - cron: "15 0 * * *"

jobs:
    test-app:
        runs-on: ubuntu-latest
        env:
            DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build Docker images
              run: docker build --build-arg="DATABASE_CONNECTION_STRING=$DATABASE_CONNECTION_STRING" -t app .
              working-directory: ./CityDistanceService/

            - name: Start services
              run: docker run app -d -e DATABASE_CONNECTION_STRING=$DATABASE_CONNECTION_STRING
              working-directory: ./CityDistanceService/

            - name: Install Newman
              run: npm install -g newman

            - name: Run Postman tests
              run: newman run ./Integration_tests/Integration.postman_collection.json
            