name: Docker Image CI/CD

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pull_req:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose -f compose.yaml build
        working-directory: ./CityDistanceService/

      - name: Start services
        run: docker compose -f compose.yaml up --wait --wait-timeout 30
        working-directory: ./CityDistanceService/

      - name: Install Newman
        run: npm install -g newman
        
      - name: Wait for services to initialize
        run: sleep 20    

    #   - name: Run Postman tests
    #     run: newman run ./Integration_tests/Integration.postman_collection.json

      - name: Stop services
        run: docker-compose down
        working-directory: ./CityDistanceService/

      - name: Compare App Version and Git Tag
        run: |
          echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          APP_VERSION=$(grep -oP 'Version\s*=\s*"\K[^"]*' ./src/Constants.cs)

          if [ "$APP_VERSION" != "$GIT_TAG" ]; then
            echo "Error: App version ($APP_VERSION) does not match the latest git tag ($GIT_TAG)."
            exit 1
          else
            echo "App version matches the latest git tag. Proceeding with the pipeline."
          fi   

      - name: Push Docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |

          echo "$DOCKER_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin

          IMAGE_NAME="$DOCKER_USERNAME/app"
          APP_VERSION=$(grep -oP 'Version\s*=\s*"\K[^"]*' ./src/Constants.cs)

          docker build -t app .

          docker tag app $IMAGE_NAME:$APP_VERSION
          docker tag app $IMAGE_NAME:latest
          docker push $IMAGE_NAME --all-tags  
        working-directory: ./CityDistanceService/
