name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-docker-app .

    - name: Run tests
      run: docker run my-docker-app dotnet test

    # - name: Push Docker image
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    #     docker tag my-docker-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/my-docker-app:latest
    #     docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-docker-app:latest