name: Docker Image CI/CD

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
  

env:
  TEST_TAG: jimbimdocker/app:test
  LATEST_TAG: jimbimdocker/app:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: List files in current directory
        run: ls -la
    
      - name: Build Docker images
        run: docker compose -f compose.yaml build

      - name: Start services
        run: docker compose -f compose.yaml up --detach --wait --wait-timeout 30

      - name: Run tests
        run: docker-compose -f compose.yaml run --rm app dotnet test

      - name: Stop services
        run: docker-compose down
      