name: Docker Image CI/CD

on:
    pull_request:
        branches: [ "main" ]
    schedule:
        - cron: "15 0 * * *"

jobs:
    test-app:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build Docker images
              env:
                DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}
              run: docker compose build
              working-directory: ./CityDistanceService/

            - name: Start services
              env:
                DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}
              run: docker compose up -d 
              working-directory: ./CityDistanceService/

            - name: Install Newman
              run: npm install -g newman

            - name: Run Postman tests
              run: newman run ./Integration_tests/Integration.postman_collection.json
            