name: Docker Image CI/CD

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Build Docker images
        env:
            DATABASE_TYPE: LOCALHOST
        run: docker compose -f compose.yaml build
        working-directory: ./CityDistanceService/

      - name: Start services
        env:
            DATABASE_TYPE: LOCALHOST
        run: docker compose -f compose.yaml up --wait --wait-timeout 30
        working-directory: ./CityDistanceService/

      - name: Stop services
        run: docker-compose down
        working-directory: ./CityDistanceService/
      