name: .NET

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    schedule:
        - cron: "15 0 * * *"

jobs:
    unit-test-app:
        runs-on: ubuntu-latest
        env:
            DATABASE_CONNECTION_STRING: "Server=127.0.0.0;User=root;Password=changeme;Database=citydistanceservice" 
        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                    dotnet-version: 8.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore
            - name: Test
              run: dotnet test --no-build --verbosity normal
